version: '3.7'

services:
  redis-server:
    image: 'redis'
  server:
    build: 
      context: .
      # dockerfile: Dockerfile.dev
      dockerfile: Dockerfile
    ports:
      - 7000:7000
    volumes:
      - /usr/src/app/node_modules
      - ./server:/usr/src/app/
